<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="$(CounterStrikeSharpVersion)" />
    <PackageReference Include="Dapper" Version="$(DapperVersion)" />
    <PackageReference Include="MySqlConnector" Version="$(MySqlConnectorVersion)" />
    <ProjectReference Include="..\..\IksAdminApi\IksAdminApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
