<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.Api" Version="$(CounterStrikeSharpVersion)"/>
    <ProjectReference Include="../../IksAdminApi/IksAdminApi.csproj"/>
  </ItemGroup>

</Project>
